
services:

  #########
  # LLMS
  #########
  llama3.2:
    provider:
      type: model
      options:
        model: ai/llama3.2

  qwen3:
    provider:
      type: model
      options:
        model: jimclark106/qwen3:4b-F16

  #########
  # MCPS
  ########
  # the mcp-gateway surfaces a restricted view of the tools
  # exposed by the MCP Toolkit
  # access gateway using SSE over http://mcp-gateway:9011/sse/...
  mcp-gateway:
    image: mcp/docker:0.0.18
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "docker-prompts:/prompts"
      - "/var/run/docker.raw.sock:/var/run/docker.raw.sock"
      - "/run/host-services/backend.sock:/backend.sock"
      - "/run/guest-services/jfs.sock:/jfs.sock"
    command:
      - --config
      - |
        registry:
          brave:
            ref: github:docker/labs-ai-tools-for-devs?ref=main&path=prompts/mcp/brave.md
          wikipedia:
            ref: github:docker/labs-ai-tools-for-devs?ref=main&path=prompts/mcp/wikipedia-mcp.md
          resend:
            ref: github:docker/labs-ai-tools-for-devs?ref=main&path=prompts/mcp/resend.md
            config:
              resend:
                reply_to: slimslenderslacks@gmail.com
                sender: slimslenderslacks@slimslenderslacks.com
        config:
          tools: brave_web_search,get_article,get_summary,get_related_topics,send-email
          name: myview

  # chat-store DB gives our app simple persistence for 
  # storing history of messages and threads
  chat-store:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=slim
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=chatstore
    volumes:
      - chat_store:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slim -d chatstore"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  initialize-chat-store-schema:
    image: initialize-chat-store-schema
    build:
      context: .
      dockerfile: Dockerfile.initialize-chat-store-schema
    environment:
      - DATABASE_URL=postgresql://slim:pass@chat-store:5432/chatstore
    depends_on:
      chat-store:
        condition: service_healthy

  ##########
  # AGENT UI
  ##########
  mcp-ui:
    image: mcp-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://slim:pass@chat-store:5432/chatstore
      - MCP_GATEWAY_URL=http://mcp-gateway:9011/sse/myview
    depends_on:
      - llama3.2
      - qwen3
      - mcp-gateway
      - chat-store
      - initialize-chat-store-schema

volumes:
  chat_store:
  docker-prompts:
    name: docker-prompts

